### ISSUE TITLE
i18n failed install

### ISSUE THREAD

**Issue by khubbitdinov** [renegadevi/nuxt-boilerplate#5]
```shell
pnpm install                         
Packages: +1176
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/tim/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1226, reused 1175, downloaded 0, added 1176, done
node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild: Running postinstall script, done in 448ms
node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild: Running postinstall script, done in 567ms

> nuxt-boilerplate@1.1.0 postinstall /Users/tim/Documents/GitHub/Account
> nuxt prepare

Nuxi 3.6.3                                                                                                                                                                              15:59:03
ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                                   nuxt:tailwindcss 15:59:04

 WARN  i18n:extend-messages is deprecated. That hook will be removed feature at the time of the v8 official release.                                                       @nuxtjs/i18n 15:59:05
If you're using it, please use i18n:registerModule instead.


 ERROR  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'                                                                                                            15:59:05

  at tryResolve (node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.12_vue@3.3.4/node_modules/@nuxtjs/i18n/dist/module.mjs:208:9)
  at async setupAlias (node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.12_vue@3.3.4/node_modules/@nuxtjs/i18n/dist/module.mjs:462:38)
  at async setup (node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.12_vue@3.3.4/node_modules/@nuxtjs/i18n/dist/module.mjs:1675:5)
  at async normalizedModule (node_modules/.pnpm/@nuxt+kit@3.6.5/node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.6.3/node_modules/@nuxt/kit/dist/index.mjs:2409:95)
  at async initNuxt (node_modules/.pnpm/nuxt@3.6.3_@types+node@18.16.19_eslint@8.44.0_typescript@5.0.2/node_modules/nuxt/dist/index.mjs:3237:7)
  at async loadNuxt (node_modules/.pnpm/nuxt@3.6.3_@types+node@18.16.19_eslint@8.44.0_typescript@5.0.2/node_modules/nuxt/dist/index.mjs:3310:5)
  at async loadNuxt (node_modules/.pnpm/@nuxt+kit@3.6.3/node_modules/@nuxt/kit/dist/index.mjs:2537:19)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.6.3/node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (node_modules/.pnpm/nuxi@3.6.3/node_modules/nuxi/dist/cli.mjs:49:20)

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by renegadevi** [comment]
Did u try clone it into a new blank folder? Because this has happened for users with i18n module when it's cloned in a pre-existing project folder or a folder with submodules.

Looking at this line: 
`> nuxt-boilerplate@1.1.0 postinstall /Users/tim/Documents/GitHub/Account`

Usually it's ending on `/nuxt-boilerplate` unless your project folder is named Account.
